default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: instarailsdb-dev

test:
  <<: *default
  database: instarailsdb-test

production:
  <<: *default
  database: instarailsdb-prod
